server:
  port: 9000
  
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
    
    producer:
      bootstrap-servers: localhost:9092 